### ISSUE TITLE
waf command doesn't work on Python 2.4

### ISSUE THREAD

**Issue by repeatedly** [retrieva/pficommon#23]
unittest_gtest.py uses b'' syntax. Python 2.4 doesn't support this syntax, so waf command fails.

Python 2.4 is a legacy and official release is ended.
I think removing python 2.4 support is better.

**Comment by eiichiroi** [comment]
* #190, #193 
  * waf was updated to 2.0.14
  * unittest_gtest was updated to latest(+ alpha)

The waf 2.0.14 support only python 2.5 to 3.4. (Python compatibility: cPython 2.5 to 3.4, Jython 2.5, IronPython, and Pypy)

So, we removed python 2.4 support now. We can build pficommon with python 3!
